//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("TasacionEnLineaBD", "FK__PagoDocum__IdCue__408F9238", "BancoCuenta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ServivioWinTasaCambio.BancoCuenta), "PagoDocumento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServivioWinTasaCambio.PagoDocumento), true)]
[assembly: EdmRelationshipAttribute("TasacionEnLineaBD", "FK__PagoDocum__IdCot__7720AD13", "CotizacionWeb", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ServivioWinTasaCambio.CotizacionWeb), "PagoDocumento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServivioWinTasaCambio.PagoDocumento), true)]

#endregion

namespace ServivioWinTasaCambio
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TasacionEnLineaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TasacionEnLineaEntities usando la cadena de conexión encontrada en la sección 'TasacionEnLineaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TasacionEnLineaEntities() : base("name=TasacionEnLineaEntities", "TasacionEnLineaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TasacionEnLineaEntities.
        /// </summary>
        public TasacionEnLineaEntities(string connectionString) : base(connectionString, "TasacionEnLineaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TasacionEnLineaEntities.
        /// </summary>
        public TasacionEnLineaEntities(EntityConnection connection) : base(connection, "TasacionEnLineaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<BancoCuenta> BancoCuenta
        {
            get
            {
                if ((_BancoCuenta == null))
                {
                    _BancoCuenta = base.CreateObjectSet<BancoCuenta>("BancoCuenta");
                }
                return _BancoCuenta;
            }
        }
        private ObjectSet<BancoCuenta> _BancoCuenta;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CotizacionWeb> CotizacionWeb
        {
            get
            {
                if ((_CotizacionWeb == null))
                {
                    _CotizacionWeb = base.CreateObjectSet<CotizacionWeb>("CotizacionWeb");
                }
                return _CotizacionWeb;
            }
        }
        private ObjectSet<CotizacionWeb> _CotizacionWeb;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PagoDocumento> PagoDocumento
        {
            get
            {
                if ((_PagoDocumento == null))
                {
                    _PagoDocumento = base.CreateObjectSet<PagoDocumento>("PagoDocumento");
                }
                return _PagoDocumento;
            }
        }
        private ObjectSet<PagoDocumento> _PagoDocumento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vwXSAValorDominio> vwXSAValorDominio
        {
            get
            {
                if ((_vwXSAValorDominio == null))
                {
                    _vwXSAValorDominio = base.CreateObjectSet<vwXSAValorDominio>("vwXSAValorDominio");
                }
                return _vwXSAValorDominio;
            }
        }
        private ObjectSet<vwXSAValorDominio> _vwXSAValorDominio;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet BancoCuenta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBancoCuenta(BancoCuenta bancoCuenta)
        {
            base.AddObject("BancoCuenta", bancoCuenta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CotizacionWeb. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCotizacionWeb(CotizacionWeb cotizacionWeb)
        {
            base.AddObject("CotizacionWeb", cotizacionWeb);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PagoDocumento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPagoDocumento(PagoDocumento pagoDocumento)
        {
            base.AddObject("PagoDocumento", pagoDocumento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vwXSAValorDominio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovwXSAValorDominio(vwXSAValorDominio vwXSAValorDominio)
        {
            base.AddObject("vwXSAValorDominio", vwXSAValorDominio);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TasacionEnLineaBD", Name="BancoCuenta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BancoCuenta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto BancoCuenta.
        /// </summary>
        /// <param name="idCuenta">Valor inicial de la propiedad IdCuenta.</param>
        /// <param name="codbco">Valor inicial de la propiedad Codbco.</param>
        /// <param name="idTipoIngreso">Valor inicial de la propiedad IdTipoIngreso.</param>
        /// <param name="idMoneda">Valor inicial de la propiedad IdMoneda.</param>
        /// <param name="esActivo">Valor inicial de la propiedad esActivo.</param>
        public static BancoCuenta CreateBancoCuenta(global::System.Guid idCuenta, global::System.Int32 codbco, global::System.Int32 idTipoIngreso, global::System.Int32 idMoneda, global::System.Boolean esActivo)
        {
            BancoCuenta bancoCuenta = new BancoCuenta();
            bancoCuenta.IdCuenta = idCuenta;
            bancoCuenta.Codbco = codbco;
            bancoCuenta.IdTipoIngreso = idTipoIngreso;
            bancoCuenta.IdMoneda = idMoneda;
            bancoCuenta.esActivo = esActivo;
            return bancoCuenta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdCuenta
        {
            get
            {
                return _IdCuenta;
            }
            set
            {
                if (_IdCuenta != value)
                {
                    OnIdCuentaChanging(value);
                    ReportPropertyChanging("IdCuenta");
                    _IdCuenta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCuenta");
                    OnIdCuentaChanged();
                }
            }
        }
        private global::System.Guid _IdCuenta;
        partial void OnIdCuentaChanging(global::System.Guid value);
        partial void OnIdCuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codbco
        {
            get
            {
                return _Codbco;
            }
            set
            {
                OnCodbcoChanging(value);
                ReportPropertyChanging("Codbco");
                _Codbco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Codbco");
                OnCodbcoChanged();
            }
        }
        private global::System.Int32 _Codbco;
        partial void OnCodbcoChanging(global::System.Int32 value);
        partial void OnCodbcoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodCta
        {
            get
            {
                return _CodCta;
            }
            set
            {
                OnCodCtaChanging(value);
                ReportPropertyChanging("CodCta");
                _CodCta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodCta");
                OnCodCtaChanged();
            }
        }
        private global::System.String _CodCta;
        partial void OnCodCtaChanging(global::System.String value);
        partial void OnCodCtaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoIngreso
        {
            get
            {
                return _IdTipoIngreso;
            }
            set
            {
                OnIdTipoIngresoChanging(value);
                ReportPropertyChanging("IdTipoIngreso");
                _IdTipoIngreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoIngreso");
                OnIdTipoIngresoChanged();
            }
        }
        private global::System.Int32 _IdTipoIngreso;
        partial void OnIdTipoIngresoChanging(global::System.Int32 value);
        partial void OnIdTipoIngresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMoneda
        {
            get
            {
                return _IdMoneda;
            }
            set
            {
                OnIdMonedaChanging(value);
                ReportPropertyChanging("IdMoneda");
                _IdMoneda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdMoneda");
                OnIdMonedaChanged();
            }
        }
        private global::System.Int32 _IdMoneda;
        partial void OnIdMonedaChanging(global::System.Int32 value);
        partial void OnIdMonedaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean esActivo
        {
            get
            {
                return _esActivo;
            }
            set
            {
                OnesActivoChanging(value);
                ReportPropertyChanging("esActivo");
                _esActivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("esActivo");
                OnesActivoChanged();
            }
        }
        private global::System.Boolean _esActivo;
        partial void OnesActivoChanging(global::System.Boolean value);
        partial void OnesActivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> IdCuentaFolio
        {
            get
            {
                return _IdCuentaFolio;
            }
            set
            {
                OnIdCuentaFolioChanging(value);
                ReportPropertyChanging("IdCuentaFolio");
                _IdCuentaFolio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCuentaFolio");
                OnIdCuentaFolioChanged();
            }
        }
        private Nullable<global::System.Guid> _IdCuentaFolio;
        partial void OnIdCuentaFolioChanging(Nullable<global::System.Guid> value);
        partial void OnIdCuentaFolioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> esImprimible
        {
            get
            {
                return _esImprimible;
            }
            set
            {
                OnesImprimibleChanging(value);
                ReportPropertyChanging("esImprimible");
                _esImprimible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("esImprimible");
                OnesImprimibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _esImprimible;
        partial void OnesImprimibleChanging(Nullable<global::System.Boolean> value);
        partial void OnesImprimibleChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TasacionEnLineaBD", "FK__PagoDocum__IdCue__408F9238", "PagoDocumento")]
        public EntityCollection<PagoDocumento> PagoDocumento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoDocumento>("TasacionEnLineaBD.FK__PagoDocum__IdCue__408F9238", "PagoDocumento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoDocumento>("TasacionEnLineaBD.FK__PagoDocum__IdCue__408F9238", "PagoDocumento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TasacionEnLineaBD", Name="CotizacionWeb")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CotizacionWeb : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CotizacionWeb.
        /// </summary>
        /// <param name="idCotizacionWeb">Valor inicial de la propiedad IdCotizacionWeb.</param>
        /// <param name="idSolicitante">Valor inicial de la propiedad IdSolicitante.</param>
        /// <param name="noCotizacion">Valor inicial de la propiedad NoCotizacion.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        /// <param name="idTipoOrden">Valor inicial de la propiedad IdTipoOrden.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad FechaRegistro.</param>
        /// <param name="noDocumento">Valor inicial de la propiedad NoDocumento.</param>
        public static CotizacionWeb CreateCotizacionWeb(global::System.Guid idCotizacionWeb, global::System.Guid idSolicitante, global::System.String noCotizacion, global::System.Decimal monto, global::System.Int32 idTipoOrden, global::System.DateTime fechaRegistro, global::System.String noDocumento)
        {
            CotizacionWeb cotizacionWeb = new CotizacionWeb();
            cotizacionWeb.IdCotizacionWeb = idCotizacionWeb;
            cotizacionWeb.IdSolicitante = idSolicitante;
            cotizacionWeb.NoCotizacion = noCotizacion;
            cotizacionWeb.Monto = monto;
            cotizacionWeb.IdTipoOrden = idTipoOrden;
            cotizacionWeb.FechaRegistro = fechaRegistro;
            cotizacionWeb.NoDocumento = noDocumento;
            return cotizacionWeb;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdCotizacionWeb
        {
            get
            {
                return _IdCotizacionWeb;
            }
            set
            {
                if (_IdCotizacionWeb != value)
                {
                    OnIdCotizacionWebChanging(value);
                    ReportPropertyChanging("IdCotizacionWeb");
                    _IdCotizacionWeb = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCotizacionWeb");
                    OnIdCotizacionWebChanged();
                }
            }
        }
        private global::System.Guid _IdCotizacionWeb;
        partial void OnIdCotizacionWebChanging(global::System.Guid value);
        partial void OnIdCotizacionWebChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> IdCotizacionPadre
        {
            get
            {
                return _IdCotizacionPadre;
            }
            set
            {
                OnIdCotizacionPadreChanging(value);
                ReportPropertyChanging("IdCotizacionPadre");
                _IdCotizacionPadre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCotizacionPadre");
                OnIdCotizacionPadreChanged();
            }
        }
        private Nullable<global::System.Guid> _IdCotizacionPadre;
        partial void OnIdCotizacionPadreChanging(Nullable<global::System.Guid> value);
        partial void OnIdCotizacionPadreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdDepartamento
        {
            get
            {
                return _IdDepartamento;
            }
            set
            {
                OnIdDepartamentoChanging(value);
                ReportPropertyChanging("IdDepartamento");
                _IdDepartamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdDepartamento");
                OnIdDepartamentoChanged();
            }
        }
        private global::System.String _IdDepartamento;
        partial void OnIdDepartamentoChanging(global::System.String value);
        partial void OnIdDepartamentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdSolicitante
        {
            get
            {
                return _IdSolicitante;
            }
            set
            {
                OnIdSolicitanteChanging(value);
                ReportPropertyChanging("IdSolicitante");
                _IdSolicitante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSolicitante");
                OnIdSolicitanteChanged();
            }
        }
        private global::System.Guid _IdSolicitante;
        partial void OnIdSolicitanteChanging(global::System.Guid value);
        partial void OnIdSolicitanteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoCotizacion
        {
            get
            {
                return _NoCotizacion;
            }
            set
            {
                OnNoCotizacionChanging(value);
                ReportPropertyChanging("NoCotizacion");
                _NoCotizacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoCotizacion");
                OnNoCotizacionChanged();
            }
        }
        private global::System.String _NoCotizacion;
        partial void OnNoCotizacionChanging(global::System.String value);
        partial void OnNoCotizacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoOrden
        {
            get
            {
                return _IdTipoOrden;
            }
            set
            {
                OnIdTipoOrdenChanging(value);
                ReportPropertyChanging("IdTipoOrden");
                _IdTipoOrden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoOrden");
                OnIdTipoOrdenChanged();
            }
        }
        private global::System.Int32 _IdTipoOrden;
        partial void OnIdTipoOrdenChanging(global::System.Int32 value);
        partial void OnIdTipoOrdenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AFavorDe
        {
            get
            {
                return _AFavorDe;
            }
            set
            {
                OnAFavorDeChanging(value);
                ReportPropertyChanging("AFavorDe");
                _AFavorDe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AFavorDe");
                OnAFavorDeChanged();
            }
        }
        private global::System.String _AFavorDe;
        partial void OnAFavorDeChanging(global::System.String value);
        partial void OnAFavorDeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private global::System.DateTime _FechaRegistro;
        partial void OnFechaRegistroChanging(global::System.DateTime value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoDocumento
        {
            get
            {
                return _NoDocumento;
            }
            set
            {
                OnNoDocumentoChanging(value);
                ReportPropertyChanging("NoDocumento");
                _NoDocumento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoDocumento");
                OnNoDocumentoChanged();
            }
        }
        private global::System.String _NoDocumento;
        partial void OnNoDocumentoChanging(global::System.String value);
        partial void OnNoDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEstadoCotizacion
        {
            get
            {
                return _IdEstadoCotizacion;
            }
            set
            {
                OnIdEstadoCotizacionChanging(value);
                ReportPropertyChanging("IdEstadoCotizacion");
                _IdEstadoCotizacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstadoCotizacion");
                OnIdEstadoCotizacionChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEstadoCotizacion;
        partial void OnIdEstadoCotizacionChanging(Nullable<global::System.Int32> value);
        partial void OnIdEstadoCotizacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Ingresada
        {
            get
            {
                return _Ingresada;
            }
            set
            {
                OnIngresadaChanging(value);
                ReportPropertyChanging("Ingresada");
                _Ingresada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ingresada");
                OnIngresadaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Ingresada;
        partial void OnIngresadaChanging(Nullable<global::System.Boolean> value);
        partial void OnIngresadaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TasacionEnLineaBD", "FK__PagoDocum__IdCot__7720AD13", "PagoDocumento")]
        public EntityCollection<PagoDocumento> PagoDocumento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoDocumento>("TasacionEnLineaBD.FK__PagoDocum__IdCot__7720AD13", "PagoDocumento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoDocumento>("TasacionEnLineaBD.FK__PagoDocum__IdCot__7720AD13", "PagoDocumento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TasacionEnLineaBD", Name="PagoDocumento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoDocumento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PagoDocumento.
        /// </summary>
        /// <param name="idPago">Valor inicial de la propiedad IdPago.</param>
        /// <param name="noDocSoporteBco">Valor inicial de la propiedad NoDocSoporteBco.</param>
        /// <param name="montoPago">Valor inicial de la propiedad MontoPago.</param>
        /// <param name="indPago">Valor inicial de la propiedad IndPago.</param>
        /// <param name="fechaPago">Valor inicial de la propiedad FechaPago.</param>
        /// <param name="horaPago">Valor inicial de la propiedad HoraPago.</param>
        /// <param name="idEstadoPago">Valor inicial de la propiedad IdEstadoPago.</param>
        /// <param name="pagoConciliado">Valor inicial de la propiedad PagoConciliado.</param>
        public static PagoDocumento CreatePagoDocumento(global::System.Guid idPago, global::System.String noDocSoporteBco, global::System.Decimal montoPago, global::System.String indPago, global::System.DateTime fechaPago, global::System.String horaPago, global::System.Int32 idEstadoPago, global::System.Boolean pagoConciliado)
        {
            PagoDocumento pagoDocumento = new PagoDocumento();
            pagoDocumento.IdPago = idPago;
            pagoDocumento.NoDocSoporteBco = noDocSoporteBco;
            pagoDocumento.MontoPago = montoPago;
            pagoDocumento.IndPago = indPago;
            pagoDocumento.FechaPago = fechaPago;
            pagoDocumento.HoraPago = horaPago;
            pagoDocumento.IdEstadoPago = idEstadoPago;
            pagoDocumento.PagoConciliado = pagoConciliado;
            return pagoDocumento;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdPago
        {
            get
            {
                return _IdPago;
            }
            set
            {
                if (_IdPago != value)
                {
                    OnIdPagoChanging(value);
                    ReportPropertyChanging("IdPago");
                    _IdPago = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPago");
                    OnIdPagoChanged();
                }
            }
        }
        private global::System.Guid _IdPago;
        partial void OnIdPagoChanging(global::System.Guid value);
        partial void OnIdPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoDocSoporteBco
        {
            get
            {
                return _NoDocSoporteBco;
            }
            set
            {
                OnNoDocSoporteBcoChanging(value);
                ReportPropertyChanging("NoDocSoporteBco");
                _NoDocSoporteBco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoDocSoporteBco");
                OnNoDocSoporteBcoChanged();
            }
        }
        private global::System.String _NoDocSoporteBco;
        partial void OnNoDocSoporteBcoChanging(global::System.String value);
        partial void OnNoDocSoporteBcoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> IdCotizacionWeb
        {
            get
            {
                return _IdCotizacionWeb;
            }
            set
            {
                OnIdCotizacionWebChanging(value);
                ReportPropertyChanging("IdCotizacionWeb");
                _IdCotizacionWeb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCotizacionWeb");
                OnIdCotizacionWebChanged();
            }
        }
        private Nullable<global::System.Guid> _IdCotizacionWeb;
        partial void OnIdCotizacionWebChanging(Nullable<global::System.Guid> value);
        partial void OnIdCotizacionWebChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MontoPago
        {
            get
            {
                return _MontoPago;
            }
            set
            {
                OnMontoPagoChanging(value);
                ReportPropertyChanging("MontoPago");
                _MontoPago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoPago");
                OnMontoPagoChanged();
            }
        }
        private global::System.Decimal _MontoPago;
        partial void OnMontoPagoChanging(global::System.Decimal value);
        partial void OnMontoPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IndPago
        {
            get
            {
                return _IndPago;
            }
            set
            {
                OnIndPagoChanging(value);
                ReportPropertyChanging("IndPago");
                _IndPago = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IndPago");
                OnIndPagoChanged();
            }
        }
        private global::System.String _IndPago;
        partial void OnIndPagoChanging(global::System.String value);
        partial void OnIndPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaPago
        {
            get
            {
                return _FechaPago;
            }
            set
            {
                OnFechaPagoChanging(value);
                ReportPropertyChanging("FechaPago");
                _FechaPago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaPago");
                OnFechaPagoChanged();
            }
        }
        private global::System.DateTime _FechaPago;
        partial void OnFechaPagoChanging(global::System.DateTime value);
        partial void OnFechaPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraPago
        {
            get
            {
                return _HoraPago;
            }
            set
            {
                OnHoraPagoChanging(value);
                ReportPropertyChanging("HoraPago");
                _HoraPago = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HoraPago");
                OnHoraPagoChanged();
            }
        }
        private global::System.String _HoraPago;
        partial void OnHoraPagoChanging(global::System.String value);
        partial void OnHoraPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstadoPago
        {
            get
            {
                return _IdEstadoPago;
            }
            set
            {
                OnIdEstadoPagoChanging(value);
                ReportPropertyChanging("IdEstadoPago");
                _IdEstadoPago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstadoPago");
                OnIdEstadoPagoChanged();
            }
        }
        private global::System.Int32 _IdEstadoPago;
        partial void OnIdEstadoPagoChanging(global::System.Int32 value);
        partial void OnIdEstadoPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SucBco
        {
            get
            {
                return _SucBco;
            }
            set
            {
                OnSucBcoChanging(value);
                ReportPropertyChanging("SucBco");
                _SucBco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SucBco");
                OnSucBcoChanged();
            }
        }
        private global::System.String _SucBco;
        partial void OnSucBcoChanging(global::System.String value);
        partial void OnSucBcoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CajaBanco
        {
            get
            {
                return _CajaBanco;
            }
            set
            {
                OnCajaBancoChanging(value);
                ReportPropertyChanging("CajaBanco");
                _CajaBanco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CajaBanco");
                OnCajaBancoChanged();
            }
        }
        private global::System.String _CajaBanco;
        partial void OnCajaBancoChanging(global::System.String value);
        partial void OnCajaBancoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaAnulacion
        {
            get
            {
                return _FechaAnulacion;
            }
            set
            {
                OnFechaAnulacionChanging(value);
                ReportPropertyChanging("FechaAnulacion");
                _FechaAnulacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaAnulacion");
                OnFechaAnulacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaAnulacion;
        partial void OnFechaAnulacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaAnulacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaConciliacion
        {
            get
            {
                return _FechaConciliacion;
            }
            set
            {
                OnFechaConciliacionChanging(value);
                ReportPropertyChanging("FechaConciliacion");
                _FechaConciliacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaConciliacion");
                OnFechaConciliacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaConciliacion;
        partial void OnFechaConciliacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaConciliacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PagoConciliado
        {
            get
            {
                return _PagoConciliado;
            }
            set
            {
                OnPagoConciliadoChanging(value);
                ReportPropertyChanging("PagoConciliado");
                _PagoConciliado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PagoConciliado");
                OnPagoConciliadoChanged();
            }
        }
        private global::System.Boolean _PagoConciliado;
        partial void OnPagoConciliadoChanging(global::System.Boolean value);
        partial void OnPagoConciliadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Identificacion
        {
            get
            {
                return _Identificacion;
            }
            set
            {
                OnIdentificacionChanging(value);
                ReportPropertyChanging("Identificacion");
                _Identificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Identificacion");
                OnIdentificacionChanged();
            }
        }
        private global::System.String _Identificacion;
        partial void OnIdentificacionChanging(global::System.String value);
        partial void OnIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String siglasBanco
        {
            get
            {
                return _siglasBanco;
            }
            set
            {
                OnsiglasBancoChanging(value);
                ReportPropertyChanging("siglasBanco");
                _siglasBanco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("siglasBanco");
                OnsiglasBancoChanged();
            }
        }
        private global::System.String _siglasBanco;
        partial void OnsiglasBancoChanging(global::System.String value);
        partial void OnsiglasBancoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoCuenta
        {
            get
            {
                return _NoCuenta;
            }
            set
            {
                OnNoCuentaChanging(value);
                ReportPropertyChanging("NoCuenta");
                _NoCuenta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoCuenta");
                OnNoCuentaChanged();
            }
        }
        private global::System.String _NoCuenta;
        partial void OnNoCuentaChanging(global::System.String value);
        partial void OnNoCuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> IdCuenta
        {
            get
            {
                return _IdCuenta;
            }
            set
            {
                OnIdCuentaChanging(value);
                ReportPropertyChanging("IdCuenta");
                _IdCuenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCuenta");
                OnIdCuentaChanged();
            }
        }
        private Nullable<global::System.Guid> _IdCuenta;
        partial void OnIdCuentaChanging(Nullable<global::System.Guid> value);
        partial void OnIdCuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoDocumentoPagado
        {
            get
            {
                return _NoDocumentoPagado;
            }
            set
            {
                OnNoDocumentoPagadoChanging(value);
                ReportPropertyChanging("NoDocumentoPagado");
                _NoDocumentoPagado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoDocumentoPagado");
                OnNoDocumentoPagadoChanged();
            }
        }
        private global::System.String _NoDocumentoPagado;
        partial void OnNoDocumentoPagadoChanging(global::System.String value);
        partial void OnNoDocumentoPagadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TasacionEnLineaBD", "FK__PagoDocum__IdCue__408F9238", "BancoCuenta")]
        public BancoCuenta BancoCuenta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BancoCuenta>("TasacionEnLineaBD.FK__PagoDocum__IdCue__408F9238", "BancoCuenta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BancoCuenta>("TasacionEnLineaBD.FK__PagoDocum__IdCue__408F9238", "BancoCuenta").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BancoCuenta> BancoCuentaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BancoCuenta>("TasacionEnLineaBD.FK__PagoDocum__IdCue__408F9238", "BancoCuenta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BancoCuenta>("TasacionEnLineaBD.FK__PagoDocum__IdCue__408F9238", "BancoCuenta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TasacionEnLineaBD", "FK__PagoDocum__IdCot__7720AD13", "CotizacionWeb")]
        public CotizacionWeb CotizacionWeb
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CotizacionWeb>("TasacionEnLineaBD.FK__PagoDocum__IdCot__7720AD13", "CotizacionWeb").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CotizacionWeb>("TasacionEnLineaBD.FK__PagoDocum__IdCot__7720AD13", "CotizacionWeb").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CotizacionWeb> CotizacionWebReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CotizacionWeb>("TasacionEnLineaBD.FK__PagoDocum__IdCot__7720AD13", "CotizacionWeb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CotizacionWeb>("TasacionEnLineaBD.FK__PagoDocum__IdCot__7720AD13", "CotizacionWeb", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TasacionEnLineaBD", Name="vwXSAValorDominio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwXSAValorDominio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vwXSAValorDominio.
        /// </summary>
        /// <param name="codigoDominio">Valor inicial de la propiedad CodigoDominio.</param>
        /// <param name="nombreDominio">Valor inicial de la propiedad NombreDominio.</param>
        /// <param name="codigoValor">Valor inicial de la propiedad CodigoValor.</param>
        /// <param name="nombreValor">Valor inicial de la propiedad NombreValor.</param>
        /// <param name="esActivoDominio">Valor inicial de la propiedad EsActivoDominio.</param>
        /// <param name="esActivoValor">Valor inicial de la propiedad EsActivoValor.</param>
        public static vwXSAValorDominio CreatevwXSAValorDominio(global::System.Int32 codigoDominio, global::System.String nombreDominio, global::System.Int32 codigoValor, global::System.String nombreValor, global::System.String esActivoDominio, global::System.String esActivoValor)
        {
            vwXSAValorDominio vwXSAValorDominio = new vwXSAValorDominio();
            vwXSAValorDominio.CodigoDominio = codigoDominio;
            vwXSAValorDominio.NombreDominio = nombreDominio;
            vwXSAValorDominio.CodigoValor = codigoValor;
            vwXSAValorDominio.NombreValor = nombreValor;
            vwXSAValorDominio.EsActivoDominio = esActivoDominio;
            vwXSAValorDominio.EsActivoValor = esActivoValor;
            return vwXSAValorDominio;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodigoDominio
        {
            get
            {
                return _CodigoDominio;
            }
            set
            {
                if (_CodigoDominio != value)
                {
                    OnCodigoDominioChanging(value);
                    ReportPropertyChanging("CodigoDominio");
                    _CodigoDominio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodigoDominio");
                    OnCodigoDominioChanged();
                }
            }
        }
        private global::System.Int32 _CodigoDominio;
        partial void OnCodigoDominioChanging(global::System.Int32 value);
        partial void OnCodigoDominioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreDominio
        {
            get
            {
                return _NombreDominio;
            }
            set
            {
                if (_NombreDominio != value)
                {
                    OnNombreDominioChanging(value);
                    ReportPropertyChanging("NombreDominio");
                    _NombreDominio = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NombreDominio");
                    OnNombreDominioChanged();
                }
            }
        }
        private global::System.String _NombreDominio;
        partial void OnNombreDominioChanging(global::System.String value);
        partial void OnNombreDominioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodigoValor
        {
            get
            {
                return _CodigoValor;
            }
            set
            {
                if (_CodigoValor != value)
                {
                    OnCodigoValorChanging(value);
                    ReportPropertyChanging("CodigoValor");
                    _CodigoValor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodigoValor");
                    OnCodigoValorChanged();
                }
            }
        }
        private global::System.Int32 _CodigoValor;
        partial void OnCodigoValorChanging(global::System.Int32 value);
        partial void OnCodigoValorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreValor
        {
            get
            {
                return _NombreValor;
            }
            set
            {
                if (_NombreValor != value)
                {
                    OnNombreValorChanging(value);
                    ReportPropertyChanging("NombreValor");
                    _NombreValor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NombreValor");
                    OnNombreValorChanged();
                }
            }
        }
        private global::System.String _NombreValor;
        partial void OnNombreValorChanging(global::System.String value);
        partial void OnNombreValorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EsActivoDominio
        {
            get
            {
                return _EsActivoDominio;
            }
            set
            {
                if (_EsActivoDominio != value)
                {
                    OnEsActivoDominioChanging(value);
                    ReportPropertyChanging("EsActivoDominio");
                    _EsActivoDominio = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EsActivoDominio");
                    OnEsActivoDominioChanged();
                }
            }
        }
        private global::System.String _EsActivoDominio;
        partial void OnEsActivoDominioChanging(global::System.String value);
        partial void OnEsActivoDominioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EsActivoValor
        {
            get
            {
                return _EsActivoValor;
            }
            set
            {
                if (_EsActivoValor != value)
                {
                    OnEsActivoValorChanging(value);
                    ReportPropertyChanging("EsActivoValor");
                    _EsActivoValor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EsActivoValor");
                    OnEsActivoValorChanged();
                }
            }
        }
        private global::System.String _EsActivoValor;
        partial void OnEsActivoValorChanging(global::System.String value);
        partial void OnEsActivoValorChanged();

        #endregion

    
    }

    #endregion

    
}
