//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ServivioWinTasaCambio
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Entities usando la cadena de conexión encontrada en la sección 'Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vwXSAValorDominio> vwXSAValorDominio
        {
            get
            {
                if ((_vwXSAValorDominio == null))
                {
                    _vwXSAValorDominio = base.CreateObjectSet<vwXSAValorDominio>("vwXSAValorDominio");
                }
                return _vwXSAValorDominio;
            }
        }
        private ObjectSet<vwXSAValorDominio> _vwXSAValorDominio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoCambio> TipoCambio
        {
            get
            {
                if ((_TipoCambio == null))
                {
                    _TipoCambio = base.CreateObjectSet<TipoCambio>("TipoCambio");
                }
                return _TipoCambio;
            }
        }
        private ObjectSet<TipoCambio> _TipoCambio;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vwXSAValorDominio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovwXSAValorDominio(vwXSAValorDominio vwXSAValorDominio)
        {
            base.AddObject("vwXSAValorDominio", vwXSAValorDominio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoCambio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoCambio(TipoCambio tipoCambio)
        {
            base.AddObject("TipoCambio", tipoCambio);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SFPRM", Name="TipoCambio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoCambio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoCambio.
        /// </summary>
        /// <param name="idTipoCambio">Valor inicial de la propiedad IdTipoCambio.</param>
        /// <param name="userName">Valor inicial de la propiedad UserName.</param>
        /// <param name="userPC">Valor inicial de la propiedad UserPC.</param>
        /// <param name="userIP">Valor inicial de la propiedad UserIP.</param>
        public static TipoCambio CreateTipoCambio(global::System.Guid idTipoCambio, global::System.String userName, global::System.String userPC, global::System.String userIP)
        {
            TipoCambio tipoCambio = new TipoCambio();
            tipoCambio.IdTipoCambio = idTipoCambio;
            tipoCambio.UserName = userName;
            tipoCambio.UserPC = userPC;
            tipoCambio.UserIP = userIP;
            return tipoCambio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdTipoCambio
        {
            get
            {
                return _IdTipoCambio;
            }
            set
            {
                if (_IdTipoCambio != value)
                {
                    OnIdTipoCambioChanging(value);
                    ReportPropertyChanging("IdTipoCambio");
                    _IdTipoCambio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTipoCambio");
                    OnIdTipoCambioChanged();
                }
            }
        }
        private global::System.Guid _IdTipoCambio;
        partial void OnIdTipoCambioChanging(global::System.Guid value);
        partial void OnIdTipoCambioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private Nullable<global::System.Decimal> _Valor;
        partial void OnValorChanging(Nullable<global::System.Decimal> value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEstatus
        {
            get
            {
                return _IdEstatus;
            }
            set
            {
                OnIdEstatusChanging(value);
                ReportPropertyChanging("IdEstatus");
                _IdEstatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstatus");
                OnIdEstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEstatus;
        partial void OnIdEstatusChanging(Nullable<global::System.Int32> value);
        partial void OnIdEstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EsActivo
        {
            get
            {
                return _EsActivo;
            }
            set
            {
                OnEsActivoChanging(value);
                ReportPropertyChanging("EsActivo");
                _EsActivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsActivo");
                OnEsActivoChanged();
            }
        }
        private Nullable<global::System.Boolean> _EsActivo;
        partial void OnEsActivoChanging(Nullable<global::System.Boolean> value);
        partial void OnEsActivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaRegistro;
        partial void OnFechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserPC
        {
            get
            {
                return _UserPC;
            }
            set
            {
                OnUserPCChanging(value);
                ReportPropertyChanging("UserPC");
                _UserPC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserPC");
                OnUserPCChanged();
            }
        }
        private global::System.String _UserPC;
        partial void OnUserPCChanging(global::System.String value);
        partial void OnUserPCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserIP
        {
            get
            {
                return _UserIP;
            }
            set
            {
                OnUserIPChanging(value);
                ReportPropertyChanging("UserIP");
                _UserIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserIP");
                OnUserIPChanged();
            }
        }
        private global::System.String _UserIP;
        partial void OnUserIPChanging(global::System.String value);
        partial void OnUserIPChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SFPRM", Name="vwXSAValorDominio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwXSAValorDominio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vwXSAValorDominio.
        /// </summary>
        /// <param name="codigoDominio">Valor inicial de la propiedad CodigoDominio.</param>
        /// <param name="nombreDominio">Valor inicial de la propiedad NombreDominio.</param>
        /// <param name="codigoValor">Valor inicial de la propiedad CodigoValor.</param>
        /// <param name="nombreValor">Valor inicial de la propiedad NombreValor.</param>
        /// <param name="esActivoDominio">Valor inicial de la propiedad EsActivoDominio.</param>
        /// <param name="esActivoValor">Valor inicial de la propiedad EsActivoValor.</param>
        public static vwXSAValorDominio CreatevwXSAValorDominio(global::System.Int32 codigoDominio, global::System.String nombreDominio, global::System.Int32 codigoValor, global::System.String nombreValor, global::System.String esActivoDominio, global::System.String esActivoValor)
        {
            vwXSAValorDominio vwXSAValorDominio = new vwXSAValorDominio();
            vwXSAValorDominio.CodigoDominio = codigoDominio;
            vwXSAValorDominio.NombreDominio = nombreDominio;
            vwXSAValorDominio.CodigoValor = codigoValor;
            vwXSAValorDominio.NombreValor = nombreValor;
            vwXSAValorDominio.EsActivoDominio = esActivoDominio;
            vwXSAValorDominio.EsActivoValor = esActivoValor;
            return vwXSAValorDominio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodigoDominio
        {
            get
            {
                return _CodigoDominio;
            }
            set
            {
                if (_CodigoDominio != value)
                {
                    OnCodigoDominioChanging(value);
                    ReportPropertyChanging("CodigoDominio");
                    _CodigoDominio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodigoDominio");
                    OnCodigoDominioChanged();
                }
            }
        }
        private global::System.Int32 _CodigoDominio;
        partial void OnCodigoDominioChanging(global::System.Int32 value);
        partial void OnCodigoDominioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreDominio
        {
            get
            {
                return _NombreDominio;
            }
            set
            {
                if (_NombreDominio != value)
                {
                    OnNombreDominioChanging(value);
                    ReportPropertyChanging("NombreDominio");
                    _NombreDominio = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NombreDominio");
                    OnNombreDominioChanged();
                }
            }
        }
        private global::System.String _NombreDominio;
        partial void OnNombreDominioChanging(global::System.String value);
        partial void OnNombreDominioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodigoValor
        {
            get
            {
                return _CodigoValor;
            }
            set
            {
                if (_CodigoValor != value)
                {
                    OnCodigoValorChanging(value);
                    ReportPropertyChanging("CodigoValor");
                    _CodigoValor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodigoValor");
                    OnCodigoValorChanged();
                }
            }
        }
        private global::System.Int32 _CodigoValor;
        partial void OnCodigoValorChanging(global::System.Int32 value);
        partial void OnCodigoValorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreValor
        {
            get
            {
                return _NombreValor;
            }
            set
            {
                if (_NombreValor != value)
                {
                    OnNombreValorChanging(value);
                    ReportPropertyChanging("NombreValor");
                    _NombreValor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NombreValor");
                    OnNombreValorChanged();
                }
            }
        }
        private global::System.String _NombreValor;
        partial void OnNombreValorChanging(global::System.String value);
        partial void OnNombreValorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EsActivoDominio
        {
            get
            {
                return _EsActivoDominio;
            }
            set
            {
                if (_EsActivoDominio != value)
                {
                    OnEsActivoDominioChanging(value);
                    ReportPropertyChanging("EsActivoDominio");
                    _EsActivoDominio = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EsActivoDominio");
                    OnEsActivoDominioChanged();
                }
            }
        }
        private global::System.String _EsActivoDominio;
        partial void OnEsActivoDominioChanging(global::System.String value);
        partial void OnEsActivoDominioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EsActivoValor
        {
            get
            {
                return _EsActivoValor;
            }
            set
            {
                if (_EsActivoValor != value)
                {
                    OnEsActivoValorChanging(value);
                    ReportPropertyChanging("EsActivoValor");
                    _EsActivoValor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EsActivoValor");
                    OnEsActivoValorChanged();
                }
            }
        }
        private global::System.String _EsActivoValor;
        partial void OnEsActivoValorChanging(global::System.String value);
        partial void OnEsActivoValorChanged();

        #endregion
    
    }

    #endregion
    
}
